### PR TITLE
New features

### PR DESCRIPTION
**Pull request by stanleymendes1**
1. Tested with PHP 7.3
2. Dependency update
3. New option to rename images

### CODE REVIEW

**Comment by CViniciusSDias** [comment]
Thank you for contributing and sending a PR. :-D

I didn't fully get your intention here... Will all the images have the same name when you run the app with this new argument?

**Comment by stanleymendes1** [comment]
Because it is a small project (little code), I use it for study. Seeking understanding of construction.
After understanding, he decides to contribute.

it is just a simple option so that the name of the image can be changed.

Thus, all images in the folder will have the same name (differentiated by the time of each one).

When downloading images from the internet, many are downloaded with random names (ex.: edcred8973swdir8.jpg), and this option will make it possible to "organize" the images with a "prefix" name.

**Comment by CViniciusSDias** [comment]
The purpose of the project is to organize pictures someone may have in it's PC.

Adding a global prefix to the images and removing the original name doesn't make much sense for what the project was originally designed.

**Comment by CViniciusSDias** [comment]
Since you would like to use this repository for studying, I can make a few suggestions of PRs you can create:
1. Update the dependencies (just like you did in this PR)
2. Write some automated (unit or integration) tests

Also... Whenever you create a PR for an open source project, give it a significant name. "New features" doesn't say much, you know what I mean?

**Comment by stanleymendes1** [comment]
> The purpose of the project is to organize pictures someone may have in it's PC.
> 
> Adding a global prefix to the images and removing the original name doesn't make much sense for what the project was originally designed.

OK! no problems

**Pull request closed without merging**
